# Build Settings
remote_theme: just-the-docs/just-the-docs

title: XIAO

# Pages
---
layout: default
title: Home
nav_order: 1
has_children: false
---
layout: default
title: TOEIC
nav_order: 2
has_children: true
---
