# Build Settings
remote_theme: just-the-docs/just-the-docs

title: YU-YI, XIAO
color_scheme: "dark"

callouts:
  warning:
    title: Warning
    color: red
  info:
    title: Info
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: yellow
  
  
